//! The customer-side GitHub Actions workflow template (PRD §5).
//!
//! Generated per repo at onboarding; the customer reviews and commits it
//! like any code. Safety properties visible in the YAML itself (the DevEx
//! buyer reads this file — it is part of the trust story):
//!
//! - `permissions:` grants exactly `contents: write` + `pull-requests:
//!   write`, nothing else; the job's `GITHUB_TOKEN` dies with the job.
//! - The agent runs with the customer's own key (`ANTHROPIC_API_KEY` from
//!   the repo's Actions secrets — a name reference, never a value through
//!   Merge0).
//! - Repair loop: up to the dispatched repair budget of test-fix iterations,
//!   then self-discard. No red PRs escape.
//! - Diff budget check before the PR opens; over budget → self-discard with
//!   the diagnosis attached (failed-run salvage).
//! - Every path ends in a callback to Merge0 with the run report.

use crate::AgentKind;

/// Render the workflow YAML for one agent kind.
pub fn workflow_yaml(agent: &AgentKind) -> String {
    let agent_command = agent.command();
    let agent_label = agent.label();
    format!(
        r#"# Generated by Merge0 — review, commit, and own this file like any code.
# Merge0 dispatches work orders; everything below runs on YOUR compute with
# YOUR keys. Merge0 never sees this job's token or your source.
name: merge0-runner

on:
  repository_dispatch:
    types: [merge0-work-order]

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write work order
        env:
          WORK_ORDER: ${{{{ toJson(github.event.client_payload.work_order) }}}}
        run: |
          printf '%s' "$WORK_ORDER" > /tmp/merge0-work-order.json
          echo "MERGE0_WORK_ORDER=/tmp/merge0-work-order.json" >> "$GITHUB_ENV"
          echo "MERGE0_REPORT_ID=$(jq -r .report_id /tmp/merge0-work-order.json)" >> "$GITHUB_ENV"
          echo "MERGE0_BRANCH=merge0/fix-$(jq -r .report_id /tmp/merge0-work-order.json)" >> "$GITHUB_ENV"

      - name: Run agent with repair budget ({agent_label})
        id: agent
        env:
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
          REPAIR_BUDGET: ${{{{ github.event.client_payload.repair_budget }}}}
        run: |
          set +e
          git checkout -b "$MERGE0_BRANCH"
          {agent_command}
          for i in $(seq 1 "$REPAIR_BUDGET"); do
            if ./merge0-test.sh > /tmp/test-output.txt 2>&1; then
              echo "tests_green=true" >> "$GITHUB_OUTPUT"; exit 0
            fi
            {agent_command_repair}
          done
          if ./merge0-test.sh > /tmp/test-output.txt 2>&1; then
            echo "tests_green=true" >> "$GITHUB_OUTPUT"; exit 0
          fi
          echo "tests_green=false" >> "$GITHUB_OUTPUT"

      - name: Measure diff footprint
        id: diff
        run: |
          FILES=$(git diff --name-only HEAD~0 | wc -l || echo 0)
          git add -A
          FILES=$(git diff --cached --name-only | wc -l)
          LINES=$(git diff --cached --numstat | awk '{{sum += $1 + $2}} END {{print sum+0}}')
          echo "files=$FILES" >> "$GITHUB_OUTPUT"
          echo "lines=$LINES" >> "$GITHUB_OUTPUT"
          BUDGET_FILES=$(jq -r .diff_budget.max_files "$MERGE0_WORK_ORDER")
          BUDGET_LINES=$(jq -r .diff_budget.max_total_lines "$MERGE0_WORK_ORDER")
          if [ "$FILES" -gt "$BUDGET_FILES" ] || [ "$LINES" -gt "$BUDGET_LINES" ]; then
            echo "within_budget=false" >> "$GITHUB_OUTPUT"
          else
            echo "within_budget=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Open PR (tests green, within budget)
        id: pr
        if: steps.agent.outputs.tests_green == 'true' && steps.diff.outputs.within_budget == 'true'
        env:
          GH_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        run: |
          git -c user.name=merge0 -c user.email=bot@merge0.invalid commit -m "$(jq -r .summary "$MERGE0_WORK_ORDER")"
          git push -u origin "$MERGE0_BRANCH"
          PR_URL=$(gh pr create --head "$MERGE0_BRANCH" \
            --title "$(jq -r .summary "$MERGE0_WORK_ORDER")" \
            --body-file <(sh .merge0/pr-body.sh))
          echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"

      - name: Report back to Merge0
        if: always()
        env:
          CALLBACK: ${{{{ github.event.client_payload.callback_url }}}}
          MERGE0_RUNNER_TOKEN: ${{{{ secrets.MERGE0_RUNNER_TOKEN }}}}
        run: |
          if [ "${{{{ steps.agent.outputs.tests_green }}}}" = "true" ] && [ "${{{{ steps.diff.outputs.within_budget }}}}" = "true" ]; then
            STATUS=opened; REASON=""
          elif [ "${{{{ steps.diff.outputs.within_budget }}}}" = "false" ]; then
            STATUS=discarded; REASON="diff budget exceeded"
          else
            STATUS=discarded; REASON="repair budget exhausted"
          fi
          DIAGNOSIS=$(tail -c 4000 /tmp/test-output.txt 2>/dev/null || true)
          jq -n \
            --arg report_id "$MERGE0_REPORT_ID" \
            --arg status "$STATUS" \
            --arg pr_url "${{{{ steps.pr.outputs.pr_url }}}}" \
            --arg branch "$MERGE0_BRANCH" \
            --arg reason "$REASON" \
            --arg diagnosis "$DIAGNOSIS" \
            --argjson files "${{{{ steps.diff.outputs.files || 0 }}}}" \
            --argjson lines "${{{{ steps.diff.outputs.lines || 0 }}}}" \
            '{{report_id: $report_id, status: $status,
              pr_url: (if $pr_url == "" then null else $pr_url end),
              branch: $branch,
              discard_reason: (if $reason == "" then null else $reason end),
              diagnosis: (if $diagnosis == "" then null else $diagnosis end),
              files_changed: $files, total_lines_changed: $lines}}' \
          | curl -sS -X POST "$CALLBACK" \
              -H "content-type: application/json" \
              -H "authorization: Bearer $MERGE0_RUNNER_TOKEN" \
              -d @-
"#,
        agent_command_repair = agent_command,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_grants_minimal_permissions_only() {
        let yaml = workflow_yaml(&AgentKind::ClaudeCode);
        assert!(yaml.contains("permissions:\n  contents: write\n  pull-requests: write"));
        for over_grant in ["administration", "packages", "id-token", "actions: write"] {
            assert!(!yaml.contains(over_grant), "over-granted {over_grant}");
        }
    }

    #[test]
    fn template_enforces_budgets_and_always_calls_back() {
        let yaml = workflow_yaml(&AgentKind::ClaudeCode);
        assert!(yaml.contains("repository_dispatch"));
        assert!(yaml.contains("merge0-work-order"));
        assert!(yaml.contains("REPAIR_BUDGET"));
        assert!(yaml.contains("diff_budget.max_files"));
        assert!(yaml.contains("if: always()"));
        assert!(yaml.contains("callback_url"));
        // Secrets are name references resolved in the customer's CI.
        assert!(yaml.contains("secrets.ANTHROPIC_API_KEY"));
        assert!(!yaml.to_lowercase().contains("sk-ant"), "no literal keys");
    }

    #[test]
    fn agent_kind_switches_the_command() {
        assert!(workflow_yaml(&AgentKind::ClaudeCode).contains("claude -p"));
        assert!(workflow_yaml(&AgentKind::CodexCli).contains("codex exec"));
        assert!(workflow_yaml(&AgentKind::Custom("./my-agent.sh".into())).contains("./my-agent.sh"));
    }
}
