//! The customer-side GitHub Actions workflow template (PRD §5, §5b, §6a).
//!
//! Generated per repo at onboarding from three inputs: the agent kind, the
//! customer's `.merge0/agent.toml` manifest, and the versioned PR-body
//! template (`config/pr-body-template.md`). The customer reviews and
//! commits the output like any code. Safety properties visible in the YAML
//! itself (the DevEx buyer reads this file — it is part of the trust
//! story):
//!
//! - `permissions:` grants exactly `contents: write` + `pull-requests:
//!   write`; the job's `GITHUB_TOKEN` dies with the job.
//! - The agent runs with the customer's own keys — the selected harness's
//!   provider key names ([`AgentKind::auth_env_names`]) and any manifest
//!   `auth_env` names are resolved from the repo's Actions secrets; values
//!   never transit Merge0.
//! - Test command comes from the manifest (`[test] command`); repair loop
//!   up to the dispatched budget, then self-discard. No red PRs escape.
//! - Diff budget measured and enforced before the PR opens.
//! - When the manifest declares `[network] egress_allow`, an egress
//!   firewall step restricts outbound traffic to those hosts plus the
//!   GitHub/Anthropic endpoints the job itself needs (PRD §5b: enforced in
//!   the runner harness, not left to prompt discipline).
//! - The PR body is rendered from the versioned template so the reviewer
//!   decides from the PR page alone (PRD §6a item 1).
//! - Every path ends in a callback to Merge0 with the run report and the
//!   manifest attribution (PRD §5b measurability).

use crate::manifest::AgentManifest;
use crate::AgentKind;

/// Infra hosts the job itself needs even under the strictest allowlist;
/// the agent's own model-provider hosts ([`AgentKind::api_hosts`]) are
/// appended per agent.
const REQUIRED_EGRESS: &[&str] = &[
    "github.com",
    "api.github.com",
    "codeload.github.com",
    "objects.githubusercontent.com",
];

/// Render the workflow YAML.
pub fn workflow_yaml(
    agent: &AgentKind,
    manifest: &AgentManifest,
    pr_body_template: &str,
) -> String {
    let test_command = manifest.test_command();
    let agent_command = agent_command(agent, manifest);
    let agent_label = agent.label();
    let allowed_tools = allowed_tools(test_command);
    let secret_env = secret_env_block(agent, manifest);
    let egress_step = egress_step(agent, manifest);
    let mcp_step = mcp_step(agent, manifest);

    format!(
        r#"# Generated by Merge0 — review, commit, and own this file like any code.
# Merge0 dispatches work orders; everything below runs on YOUR compute with
# YOUR keys. Merge0 never sees this job's token or your source.
name: merge0-runner

on:
  repository_dispatch:
    types: [merge0-work-order]

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write work order
        env:
          WORK_ORDER: ${{{{ toJson(github.event.client_payload.work_order) }}}}
          ATTRIBUTION: ${{{{ toJson(github.event.client_payload.attribution) }}}}
        run: |
          printf '%s' "$WORK_ORDER" > /tmp/merge0-work-order.json
          printf '%s' "$ATTRIBUTION" > /tmp/merge0-attribution.json
          echo "MERGE0_WORK_ORDER=/tmp/merge0-work-order.json" >> "$GITHUB_ENV"
          echo "MERGE0_REPORT_ID=$(jq -r .report_id /tmp/merge0-work-order.json)" >> "$GITHUB_ENV"
          echo "MERGE0_BRANCH=merge0/fix-$(jq -r .report_id /tmp/merge0-work-order.json)" >> "$GITHUB_ENV"
{egress_step}{mcp_step}
      - name: Run agent with repair budget ({agent_label})
        id: agent
        env:
          REPAIR_BUDGET: ${{{{ github.event.client_payload.repair_budget }}}}
{secret_env}        run: |
          set +e
          git checkout -b "$MERGE0_BRANCH"
          {agent_command}
          for i in $(seq 1 "$REPAIR_BUDGET"); do
            if {test_command} > /tmp/test-output.txt 2>&1; then
              echo "tests_green=true" >> "$GITHUB_OUTPUT"; exit 0
            fi
            {agent_command}
          done
          if {test_command} > /tmp/test-output.txt 2>&1; then
            echo "tests_green=true" >> "$GITHUB_OUTPUT"; exit 0
          fi
          echo "tests_green=false" >> "$GITHUB_OUTPUT"

      - name: Measure diff footprint
        id: diff
        run: |
          git add -A
          FILES=$(git diff --cached --name-only | wc -l)
          LINES=$(git diff --cached --numstat | awk '{{sum += $1 + $2}} END {{print sum+0}}')
          echo "files=$FILES" >> "$GITHUB_OUTPUT"
          echo "lines=$LINES" >> "$GITHUB_OUTPUT"
          BUDGET_FILES=$(jq -r .diff_budget.max_files "$MERGE0_WORK_ORDER")
          BUDGET_LINES=$(jq -r .diff_budget.max_total_lines "$MERGE0_WORK_ORDER")
          if [ "$FILES" -gt "$BUDGET_FILES" ] || [ "$LINES" -gt "$BUDGET_LINES" ]; then
            echo "within_budget=false" >> "$GITHUB_OUTPUT"
          else
            echo "within_budget=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Render PR body from the versioned template
        id: body
        if: steps.agent.outputs.tests_green == 'true' && steps.diff.outputs.within_budget == 'true'
        run: |
          cat > /tmp/merge0-pr-template.md <<'MERGE0_TEMPLATE'
{indented_template}
MERGE0_TEMPLATE
          export MERGE0_SUMMARY="$(jq -r .summary "$MERGE0_WORK_ORDER")"
          export MERGE0_SUCCESS_CRITERIA="$(jq -r .success_criteria "$MERGE0_WORK_ORDER")"
          export MERGE0_CONSTRAINTS="$(jq -r '.constraints // "none stated"' "$MERGE0_WORK_ORDER")"
          export MERGE0_SUSPECT_CHANGE="$(jq -r '.suspect_change // "unknown"' "$MERGE0_WORK_ORDER")"
          export MERGE0_EVIDENCE="$(jq -r '[.evidence[] | "- [\(.label)](\(.url))"] | join("\n")' "$MERGE0_WORK_ORDER")"
          export MERGE0_REPRO="$(jq -r .repro "$MERGE0_WORK_ORDER")"
          export MERGE0_TEST_COMMAND={test_command_quoted}
          export MERGE0_FILES_CHANGED="${{{{ steps.diff.outputs.files }}}}"
          export MERGE0_LINES_CHANGED="${{{{ steps.diff.outputs.lines }}}}"
          export MERGE0_BUDGET_FILES="$(jq -r .diff_budget.max_files "$MERGE0_WORK_ORDER")"
          export MERGE0_BUDGET_LINES="$(jq -r .diff_budget.max_total_lines "$MERGE0_WORK_ORDER")"
          export MERGE0_REPORT_ID="$MERGE0_REPORT_ID"
          envsubst < /tmp/merge0-pr-template.md > /tmp/merge0-pr-body.md

      - name: Open PR (tests green, within budget)
        id: pr
        if: steps.agent.outputs.tests_green == 'true' && steps.diff.outputs.within_budget == 'true'
        env:
          GH_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        run: |
          git -c user.name=merge0 -c user.email=bot@merge0.invalid commit -m "$(jq -r .summary "$MERGE0_WORK_ORDER")"
          git push -u origin "$MERGE0_BRANCH"
          PR_URL=$(gh pr create --head "$MERGE0_BRANCH" \
            --title "$(jq -r .summary "$MERGE0_WORK_ORDER")" \
            --body-file /tmp/merge0-pr-body.md)
          echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"

      - name: Report back to Merge0
        if: always()
        env:
          CALLBACK: ${{{{ github.event.client_payload.callback_url }}}}
          MERGE0_RUNNER_TOKEN: ${{{{ secrets.MERGE0_RUNNER_TOKEN }}}}
        run: |
          if [ "${{{{ steps.agent.outputs.tests_green }}}}" = "true" ] && [ "${{{{ steps.diff.outputs.within_budget }}}}" = "true" ]; then
            STATUS=opened; REASON=""
          elif [ "${{{{ steps.diff.outputs.within_budget }}}}" = "false" ]; then
            STATUS=discarded; REASON="diff budget exceeded"
          else
            STATUS=discarded; REASON="repair budget exhausted"
          fi
          DIAGNOSIS=$(tail -c 4000 /tmp/test-output.txt 2>/dev/null || true)
          EXTENSIONS=$(cat /tmp/merge0-attribution.json 2>/dev/null || echo null)
          jq -n \
            --arg report_id "$MERGE0_REPORT_ID" \
            --arg status "$STATUS" \
            --arg pr_url "${{{{ steps.pr.outputs.pr_url }}}}" \
            --arg branch "$MERGE0_BRANCH" \
            --arg reason "$REASON" \
            --arg diagnosis "$DIAGNOSIS" \
            --argjson files "${{{{ steps.diff.outputs.files || 0 }}}}" \
            --argjson lines "${{{{ steps.diff.outputs.lines || 0 }}}}" \
            --argjson extensions "$EXTENSIONS" \
            '{{report_id: $report_id, status: $status,
              pr_url: (if $pr_url == "" then null else $pr_url end),
              branch: $branch,
              discard_reason: (if $reason == "" then null else $reason end),
              diagnosis: (if $diagnosis == "" then null else $diagnosis end),
              files_changed: $files, total_lines_changed: $lines,
              extensions: $extensions}}' \
          | curl -sS -X POST "$CALLBACK" \
              -H "content-type: application/json" \
              -H "authorization: Bearer $MERGE0_RUNNER_TOKEN" \
              -d @-
"#,
        indented_template = indent(pr_body_template.trim_end(), "          "),
        test_command_quoted = shell_single_quote(test_command),
    )
    .replace("__MERGE0_ALLOWED_TOOLS__", &allowed_tools)
}

/// The agent invocation. For Claude Code the tool allowlist is derived from
/// the manifest: edit/write/git plus the test command's leading word —
/// deliberately NOT `Bash(npx *)` or any open-ended network-capable tool
/// (audit finding M5).
fn agent_command(agent: &AgentKind, manifest: &AgentManifest) -> String {
    match agent {
        AgentKind::ClaudeCode => {
            let mcp = if manifest.mcps.is_empty() {
                String::new()
            } else {
                " --mcp-config /tmp/merge0-mcp.json".to_string()
            };
            format!(
                "claude -p \"$(cat \"$MERGE0_WORK_ORDER\")\" --allowedTools \"__MERGE0_ALLOWED_TOOLS__\"{mcp}"
            )
        }
        other => other.command(),
    }
}

fn allowed_tools(test_command: &str) -> String {
    let test_word = test_command.split_whitespace().next().unwrap_or("true");
    format!("Edit,Write,Bash(git *),Bash({test_word} *)")
}

/// The agent's own provider keys plus manifest `auth_env` names become
/// secret mappings on the agent step — name-only references resolved by
/// the customer's own CI (PRD §5b).
fn secret_env_block(agent: &AgentKind, manifest: &AgentManifest) -> String {
    agent
        .auth_env_names()
        .iter()
        .copied()
        .chain(manifest.auth_env_names())
        .map(|name| format!("          {name}: ${{{{ secrets.{name} }}}}\n"))
        .collect()
}

/// Egress allowlist enforcement (PRD §5b): default-deny outbound with
/// explicit holes for the manifest hosts + required infra + the agent's
/// own model-provider hosts. Only generated when the manifest declares an
/// allowlist.
fn egress_step(agent: &AgentKind, manifest: &AgentManifest) -> String {
    let allow = manifest.egress_allow();
    if allow.is_empty() {
        return String::new();
    }
    let hosts: Vec<String> = REQUIRED_EGRESS
        .iter()
        .chain(agent.api_hosts())
        .map(|h| h.to_string())
        .chain(allow.iter().cloned())
        .collect();
    format!(
        r#"
      - name: Enforce egress allowlist (from .merge0/agent.toml)
        run: |
          set -e
          for host in {hosts}; do
            for ip in $(getent ahostsv4 "$host" | awk '{{print $1}}' | sort -u); do
              sudo iptables -A OUTPUT -d "$ip" -j ACCEPT
            done
          done
          sudo iptables -A OUTPUT -o lo -j ACCEPT
          sudo iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
          sudo iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT
          sudo iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
          sudo iptables -A OUTPUT -j REJECT
"#,
        hosts = hosts.join(" "),
    )
}

/// MCP configuration for Claude Code: generated from the manifest, with
/// env values referencing the job environment (populated from the
/// customer's secrets by [`secret_env_block`]) — the credential value never
/// appears in the workflow file or transits Merge0.
fn mcp_step(agent: &AgentKind, manifest: &AgentManifest) -> String {
    if manifest.mcps.is_empty() || !matches!(agent, AgentKind::ClaudeCode) {
        return String::new();
    }
    let servers: serde_json::Value = manifest
        .mcps
        .iter()
        .map(|m| {
            let mut server = serde_json::json!({ "command": m.command });
            if let Some(auth_env) = &m.auth_env {
                server["env"] = serde_json::json!({ auth_env: format!("${{{auth_env}}}") });
            }
            (m.name.clone(), server)
        })
        .collect::<serde_json::Map<String, serde_json::Value>>()
        .into();
    let config = serde_json::to_string_pretty(&serde_json::json!({ "mcpServers": servers }))
        .expect("mcp config serializes");
    format!(
        r#"
      - name: Write MCP config (from .merge0/agent.toml)
        run: |
          cat > /tmp/merge0-mcp.json <<'MERGE0_MCP'
{config}
MERGE0_MCP
"#,
        config = indent(&config, "          "),
    )
}

fn indent(text: &str, prefix: &str) -> String {
    text.lines()
        .map(|line| {
            if line.is_empty() {
                String::new()
            } else {
                format!("{prefix}{line}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn shell_single_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', r"'\''"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::AgentManifest;

    fn template() -> &'static str {
        "${MERGE0_SUMMARY}\n\nEvidence:\n${MERGE0_EVIDENCE}\nBudget: ${MERGE0_BUDGET_FILES}"
    }

    fn full_manifest() -> AgentManifest {
        AgentManifest::parse(
            r#"
            [[mcp]]
            name = "internal-api"
            command = "npx our-api-mcp"
            auth_env = "INTERNAL_API_KEY"

            [network]
            egress_allow = ["api.internal.example.com"]

            [test]
            command = "cargo test --workspace"
            "#,
        )
        .unwrap()
    }

    #[test]
    fn template_grants_minimal_permissions_only() {
        let yaml = workflow_yaml(
            &AgentKind::ClaudeCode,
            &AgentManifest::default(),
            template(),
        );
        assert!(yaml.contains("permissions:\n  contents: write\n  pull-requests: write"));
        for over_grant in ["administration", "packages", "id-token", "actions: write"] {
            assert!(!yaml.contains(over_grant), "over-granted {over_grant}");
        }
    }

    #[test]
    fn no_dangling_file_references_and_test_command_is_manifest_driven() {
        let yaml = workflow_yaml(&AgentKind::ClaudeCode, &full_manifest(), template());
        // The audit's C3: the old template shelled out to files that never
        // existed. Everything referenced is now generated in-job.
        assert!(!yaml.contains("pr-body.sh"));
        assert!(!yaml.contains("./merge0-test.sh"));
        assert!(yaml.contains("cargo test --workspace > /tmp/test-output.txt"));
        assert!(yaml.contains("envsubst < /tmp/merge0-pr-template.md"));
        assert!(yaml.contains("--body-file /tmp/merge0-pr-body.md"));
        // The versioned template content itself is embedded.
        assert!(yaml.contains("${MERGE0_SUMMARY}"));
    }

    #[test]
    fn default_manifest_uses_documented_default_test_command() {
        let yaml = workflow_yaml(
            &AgentKind::ClaudeCode,
            &AgentManifest::default(),
            template(),
        );
        assert!(yaml.contains("./merge0-test.sh > /tmp/test-output.txt"));
    }

    #[test]
    fn allowlist_is_scoped_no_npx_and_derived_from_test_command() {
        let yaml = workflow_yaml(&AgentKind::ClaudeCode, &full_manifest(), template());
        assert!(yaml.contains("--allowedTools \"Edit,Write,Bash(git *),Bash(cargo *)\""));
        assert!(!yaml.contains("Bash(npx *)"), "audit M5: npx must be gone");
    }

    #[test]
    fn mcp_and_secret_wiring_are_name_references_only() {
        let yaml = workflow_yaml(&AgentKind::ClaudeCode, &full_manifest(), template());
        assert!(yaml.contains("INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}"));
        assert!(yaml.contains("--mcp-config /tmp/merge0-mcp.json"));
        assert!(yaml.contains("\"env\": {"));
        assert!(yaml.contains("\"INTERNAL_API_KEY\": \"${INTERNAL_API_KEY}\""));
        // No literal secret values anywhere.
        assert!(!yaml.to_lowercase().contains("sk-ant"));
    }

    #[test]
    fn egress_enforcement_generated_only_when_declared() {
        let with = workflow_yaml(&AgentKind::ClaudeCode, &full_manifest(), template());
        assert!(with.contains("Enforce egress allowlist"));
        assert!(with.contains("api.internal.example.com"));
        assert!(
            with.contains("api.anthropic.com"),
            "infra hosts stay reachable"
        );
        assert!(
            with.contains("iptables -A OUTPUT -j REJECT"),
            "default deny"
        );

        let without = workflow_yaml(
            &AgentKind::ClaudeCode,
            &AgentManifest::default(),
            template(),
        );
        assert!(!without.contains("iptables"));
    }

    #[test]
    fn callback_reports_attribution_and_always_fires() {
        let yaml = workflow_yaml(&AgentKind::ClaudeCode, &full_manifest(), template());
        assert!(yaml.contains("if: always()"));
        assert!(yaml.contains("--argjson extensions"));
        assert!(yaml.contains("merge0-attribution.json"));
        assert!(yaml.contains("REPAIR_BUDGET"));
        assert!(yaml.contains("diff_budget.max_files"));
    }

    #[test]
    fn agent_kind_switches_the_command() {
        assert!(workflow_yaml(
            &AgentKind::ClaudeCode,
            &AgentManifest::default(),
            template()
        )
        .contains("claude -p"));
        assert!(
            workflow_yaml(&AgentKind::CodexCli, &AgentManifest::default(), template())
                .contains("codex exec")
        );
        assert!(workflow_yaml(
            &AgentKind::Custom("./my-agent.sh".into()),
            &AgentManifest::default(),
            template()
        )
        .contains("./my-agent.sh"));
    }

    #[test]
    fn every_preset_embeds_its_headless_command_and_provider_secrets() {
        // (agent, command fragment, secret that must be mapped on the step)
        let cases: &[(AgentKind, &str, &str)] = &[
            (AgentKind::ClaudeCode, "claude -p", "ANTHROPIC_API_KEY"),
            (
                AgentKind::CodexCli,
                "codex exec --sandbox workspace-write",
                "OPENAI_API_KEY",
            ),
            (
                AgentKind::GeminiCli,
                "gemini -p \"$(cat \"$MERGE0_WORK_ORDER\")\" --approval-mode=yolo",
                "GEMINI_API_KEY",
            ),
            (
                AgentKind::Aider,
                "aider --message \"$(cat \"$MERGE0_WORK_ORDER\")\" --yes-always --no-auto-commits",
                "ANTHROPIC_API_KEY",
            ),
            (
                AgentKind::Opencode,
                "opencode run \"$(cat \"$MERGE0_WORK_ORDER\")\"",
                "OPENAI_API_KEY",
            ),
            (
                AgentKind::CursorCli,
                "cursor-agent -p \"$(cat \"$MERGE0_WORK_ORDER\")\"",
                "CURSOR_API_KEY",
            ),
        ];
        for (agent, fragment, secret) in cases {
            let yaml = workflow_yaml(agent, &AgentManifest::default(), template());
            assert!(
                yaml.contains(fragment),
                "{} missing command fragment {fragment:?}",
                agent.label()
            );
            assert!(
                yaml.contains(&format!("{secret}: ${{{{ secrets.{secret} }}}}")),
                "{} missing secret mapping for {secret}",
                agent.label()
            );
            // Every mapped secret is a name reference, never a value.
            assert!(!yaml.to_lowercase().contains("sk-ant"));
        }
    }

    #[test]
    fn egress_allowlist_includes_the_agents_own_provider_hosts() {
        let cases: &[(AgentKind, &str)] = &[
            (AgentKind::ClaudeCode, "api.anthropic.com"),
            (AgentKind::CodexCli, "api.openai.com"),
            (AgentKind::GeminiCli, "generativelanguage.googleapis.com"),
            (AgentKind::CursorCli, "api.cursor.com"),
        ];
        for (agent, host) in cases {
            let yaml = workflow_yaml(agent, &full_manifest(), template());
            assert!(
                yaml.contains(host),
                "{} egress missing provider host {host}",
                agent.label()
            );
            assert!(yaml.contains("api.internal.example.com"));
        }
        // An agent that doesn't use Anthropic must not open a hole to it.
        let codex = workflow_yaml(&AgentKind::CodexCli, &full_manifest(), template());
        assert!(!codex.contains("api.anthropic.com"));
    }

    #[test]
    fn aider_never_auto_commits_because_the_workflow_owns_the_commit() {
        // The diff step measures `git diff --cached` against the base
        // commit and the PR step makes the commit; an agent that commits
        // on its own breaks both. This pins the flag that prevents it.
        let yaml = workflow_yaml(&AgentKind::Aider, &AgentManifest::default(), template());
        assert!(yaml.contains("--no-auto-commits"));
        assert!(yaml.contains("--yes-always"));
    }
}
